name: auto-aur-update
on:
  watch:
    types: [started]
  schedule:
  - cron: "30 2 * * *"
  workflow_dispatch:
  
jobs:
  # This workflow contains a single job called "build"
  UpdatePkg:
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - cursor-appimage

    runs-on: ubuntu-latest
#    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
        
    steps:
      - uses: actions/checkout@v2
      - uses: ./build-aur-action
        with:
          pkgname: ${{ matrix.PKGBUILDs }}
          pkgdir: ${{ matrix.PKGBUILDs }}
          
      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@v2.7.0
        with:
          pkgname: ${{ matrix.PKGBUILDs }}
          pkgbuild: ${{ matrix.PKGBUILDs }}/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
          ssh_keyscan_types: rsa,dsa,ecdsa,ed25519
          allow_empty_commits: false
    
  Task:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
         fetch-depth: 0
    - name: Make Time log #Api调用
      run: | 
        echo `date +"%Y-%m-%d %H:%M:%S"` begin >> time.log     
    - name: Commit #上传新的refresh_token到仓库
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -m "update new time.log" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
